version: '3.9'

services:
  payload_evergreen:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    env_file:
      - .env
    volumes:
      - ./public/media:/app/public/media:rw
    user: '1001:1001'
    restart: always
