# version: '3.9'

services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.watch=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.email=contact@christdev.com
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web
    ports:
      - '81:80'
      - '444:443'
      - '8081:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./letsencrypt:/letsencrypt
      - ./public/media:/media
    networks: # Connect to the 'web' network
      - evergreen
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    restart: always

  payload:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.payload.rule=Host(`evergreenpsychiatrygroup.com`)'
      - 'traefik.http.routers.payload.entrypoints=websecure'
      - 'traefik.http.routers.payload.tls=true'
      - 'traefik.http.routers.payload.tls.certresolver=myresolver'
      - 'traefik.http.routers.payload-media.rule=PathPrefix(`/media`)'
      - 'traefik.http.routers.payload-media.entrypoints=websecure'
      - 'traefik.http.routers.payload-media.tls=true'
      - 'traefik.http.routers.payload-media.tls.certresolver=myresolver'
      - 'traefik.http.services.payload.loadbalancer.server.port=3000'
      - 'traefik.http.middlewares.large-upload.headers.customrequestheaders.Content-Length=524288000'
      - 'traefik.http.routers.payload.middlewares=large-upload'
    networks:
      - evergreen
    depends_on:
      - traefik
    volumes:
      - ./public/media:/app/public/media
    restart: always

networks:
  evergreen:
    external: false

volumes:
  letsencrypt:
