version: '3'

services:
  # payload:
  #   image: node:18-alpine
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/home/node/app
  #     - node_modules:/home/node/app/node_modules
  #   working_dir: /home/node/app/
  #   command: sh -c "npm install -g pnpm && pnpm dev"
  #   depends_on:
  #     - mongo
  #   env_file:
  #     - .env
  #   networks:
  #     - evergreen

  mongo:
    image: mongo:latest
    ports:
      - '27019:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none
    # networks:
    #   - evergreen

volumes:
  data:
  node_modules:

# networks:
#   evergreen:
#     driver: bridge
