import { bgColorPickerAll } from '@/fields/bgColorPicker'
import { Block } from 'payload'

export const SpacingBlock: Block = {
  slug: 'spacing',
  interfaceName: 'SpacingBlock',
  labels: {
    plural: 'Spacing',
    singular: 'Spacing',
  },
  fields: [
    {
      name: 'spacing',
      type: 'select',
      required: true,
      defaultValue: ['pb-0', 'md:pb-8', 'lg:pb-12', 'xl:pb-16', '2xl:pb-32'],
      hasMany: true,
      options: [
        { label: 'None', value: 'pb-0' },
        { label: 'Space 1', value: 'pb-1' },
        { label: 'Space 2', value: 'pb-2' },
        { label: 'Space 4', value: 'pb-4' },
        { label: 'Space 8', value: 'pb-8' },
        { label: 'Space 10', value: 'pb-10' },
        { label: 'Space 12', value: 'pb-12' },
        { label: 'Space 16', value: 'pb-16' },
        { label: 'Space 20', value: 'pb-20' },
        { label: 'Space 24', value: 'pb-24' },
        { label: 'Space 32', value: 'pb-32' },
        { label: 'Space 40', value: 'pb-40' },
        { label: 'Space 48', value: 'pb-48' },
        { label: 'Space 56', value: 'pb-56' },
        { label: 'Space 64', value: 'pb-64' },
        { label: 'Space 72', value: 'pb-72' },
        { label: 'Space 80', value: 'pb-80' },
        // add options for different screen sizes
        { label: 'md:None', value: 'md:pb-0' },
        { label: 'md:Space 1', value: 'md:pb-1' },
        { label: 'md:Space 2', value: 'md:pb-2' },
        { label: 'md:Space 4', value: 'md:pb-4' },
        { label: 'md:Space 8', value: 'md:pb-8' },
        { label: 'md:Space 10', value: 'md:pb-10' },
        { label: 'md:Space 12', value: 'md:pb-12' },
        { label: 'md:Space 16', value: 'md:pb-16' },
        { label: 'md:Space 20', value: 'md:pb-20' },
        { label: 'md:Space 24', value: 'md:pb-24' },
        { label: 'md:Space 32', value: 'md:pb-32' },
        { label: 'md:Space 40', value: 'md:pb-40' },
        { label: 'md:Space 48', value: 'md:pb-48' },
        { label: 'md:Space 56', value: 'md:pb-56' },
        { label: 'md:Space 64', value: 'md:pb-64' },
        { label: 'md:Space 72', value: 'md:pb-72' },
        { label: 'md:Space 80', value: 'md:pb-80' },

        { label: 'lg:None', value: 'lg:pb-0' },
        { label: 'lg:Space 1', value: 'lg:pb-1' },
        { label: 'lg:Space 2', value: 'lg:pb-2' },
        { label: 'lg:Space 4', value: 'lg:pb-4' },
        { label: 'lg:Space 8', value: 'lg:pb-8' },
        { label: 'lg:Space 10', value: 'lg:pb-10' },
        { label: 'lg:Space 12', value: 'lg:pb-12' },
        { label: 'lg:Space 16', value: 'lg:pb-16' },
        { label: 'lg:Space 20', value: 'lg:pb-20' },
        { label: 'lg:Space 24', value: 'lg:pb-24' },
        { label: 'lg:Space 32', value: 'lg:pb-32' },
        { label: 'lg:Space 40', value: 'lg:pb-40' },
        { label: 'lg:Space 48', value: 'lg:pb-48' },
        { label: 'lg:Space 56', value: 'lg:pb-56' },
        { label: 'lg:Space 64', value: 'lg:pb-64' },
        { label: 'lg:Space 72', value: 'lg:pb-72' },
        { label: 'lg:Space 80', value: 'lg:pb-80' },
        // XL options
        { label: 'xl:None', value: 'xl:pb-0' },
        { label: 'xl:Space 1', value: 'xl:pb-1' },
        { label: 'xl:Space 2', value: 'xl:pb-2' },
        { label: 'xl:Space 4', value: 'xl:pb-4' },
        { label: 'xl:Space 8', value: 'xl:pb-8' },
        { label: 'xl:Space 10', value: 'xl:pb-10' },
        { label: 'xl:Space 12', value: 'xl:pb-12' },
        { label: 'xl:Space 16', value: 'xl:pb-16' },
        { label: 'xl:Space 20', value: 'xl:pb-20' },
        { label: 'xl:Space 24', value: 'xl:pb-24' },
        { label: 'xl:Space 32', value: 'xl:pb-32' },
        { label: 'xl:Space 40', value: 'xl:pb-40' },
        { label: 'xl:Space 48', value: 'xl:pb-48' },
        { label: 'xl:Space 56', value: 'xl:pb-56' },
        { label: 'xl:Space 64', value: 'xl:pb-64' },
        { label: 'xl:Space 72', value: 'xl:pb-72' },
        { label: 'xl:Space 80', value: 'xl:pb-80' },
        // 2XL options
        { label: '2xl:None', value: '2xl:pb-0' },
        { label: '2xl:Space 1', value: '2xl:pb-1' },
        { label: '2xl:Space 2', value: '2xl:pb-2' },
        { label: '2xl:Space 4', value: '2xl:pb-4' },
        { label: '2xl:Space 8', value: '2xl:pb-8' },
        { label: '2xl:Space 10', value: '2xl:pb-10' },
        { label: '2xl:Space 12', value: '2xl:pb-12' },
        { label: '2xl:Space 16', value: '2xl:pb-16' },
        { label: '2xl:Space 20', value: '2xl:pb-20' },
        { label: '2xl:Space 24', value: '2xl:pb-24' },
        { label: '2xl:Space 32', value: '2xl:pb-32' },
        { label: '2xl:Space 40', value: '2xl:pb-40' },
        { label: '2xl:Space 48', value: '2xl:pb-48' },
        { label: '2xl:Space 56', value: '2xl:pb-56' },
        { label: '2xl:Space 64', value: '2xl:pb-64' },
        { label: '2xl:Space 72', value: '2xl:pb-72' },
        { label: '2xl:Space 80', value: '2xl:pb-80' },
        // 3XL options
        { label: '3xl:None', value: '3xl:pb-0' },
        { label: '3xl:Space 1', value: '3xl:pb-1' },
        { label: '3xl:Space 2', value: '3xl:pb-2' },
        { label: '3xl:Space 4', value: '3xl:pb-4' },
        { label: '3xl:Space 8', value: '3xl:pb-8' },
        { label: '3xl:Space 10', value: '3xl:pb-10' },
        { label: '3xl:Space 12', value: '3xl:pb-12' },
        { label: '3xl:Space 16', value: '3xl:pb-16' },
        { label: '3xl:Space 20', value: '3xl:pb-20' },
        { label: '3xl:Space 24', value: '3xl:pb-24' },
        { label: '3xl:Space 32', value: '3xl:pb-32' },
        { label: '3xl:Space 40', value: '3xl:pb-40' },
        { label: '3xl:Space 48', value: '3xl:pb-48' },
        { label: '3xl:Space 56', value: '3xl:pb-56' },
        { label: '3xl:Space 64', value: '3xl:pb-64' },
        { label: '3xl:Space 72', value: '3xl:pb-72' },
        { label: '3xl:Space 80', value: '3xl:pb-80' },
      ],
    },
    bgColorPickerAll({
      overrides: {
        defaultValue: 'bg-transparent',
      },
    }),
    {
      name: 'width',
      type: 'select',
      required: true,
      defaultValue: ['w-full'],
      hasMany: true,
      options: [
        { label: 'Full', value: 'w-full' },
        { label: 'Half', value: 'w-1/2' },
        { label: 'Third', value: 'w-1/3' },
        { label: 'Two Thirds', value: 'w-2/3' },
        { label: 'Quarter', value: 'w-1/4' },
        { label: 'Three Quarters', value: 'w-3/4' },
        { label: 'One Fifth', value: 'w-1/5' },
        { label: 'Two Fifths', value: 'w-2/5' },
        { label: 'Three Fifths', value: 'w-3/5' },
        { label: 'Four Fifths', value: 'w-4/5' },
        // add options for different screen sizes
        { label: 'md:Full', value: 'md:w-full' },
        { label: 'md:Half', value: 'md:w-1/2' },
        { label: 'md:Third', value: 'md:w-1/3' },
        { label: 'md:Two Thirds', value: 'md:w-2/3' },
        { label: 'md:Quarter', value: 'md:w-1/4' },
        { label: 'md:Three Quarters', value: 'md:w-3/4' },
        { label: 'md:One Fifth', value: 'md:w-1/5' },
        { label: 'md:Two Fifths', value: 'md:w-2/5' },
        { label: 'md:Three Fifths', value: 'md:w-3/5' },
        { label: 'md:Four Fifths', value: 'md:w-4/5' },
        { label: 'lg:Full', value: 'lg:w-full' },
        { label: 'lg:Half', value: 'lg:w-1/2' },
        { label: 'lg:Third', value: 'lg:w-1/3' },
        { label: 'lg:Two Thirds', value: 'lg:w-2/3' },
        { label: 'lg:Quarter', value: 'lg:w-1/4' },
        { label: 'lg:Three Quarters', value: 'lg:w-3/4' },
        { label: 'lg:One Fifth', value: 'lg:w-1/5' },
        { label: 'lg:Two Fifths', value: 'lg:w-2/5' },
        { label: 'lg:Three Fifths', value: 'lg:w-3/5' },
        { label: 'lg:Four Fifths', value: 'lg:w-4/5' },
        { label: 'xl:Full', value: 'xl:w-full' },
        { label: 'xl:Half', value: 'xl:w-1/2' },
        { label: 'xl:Third', value: 'xl:w-1/3' },
        { label: 'xl:Two Thirds', value: 'xl:w-2/3' },
        { label: 'xl:Quarter', value: 'xl:w-1/4' },
        { label: 'xl:Three Quarters', value: 'xl:w-3/4' },
        { label: 'xl:One Fifth', value: 'xl:w-1/5' },
        { label: 'xl:Two Fifths', value: 'xl:w-2/5' },
        { label: 'xl:Three Fifths', value: 'xl:w-3/5' },
        { label: 'xl:Four Fifths', value: 'xl:w-4/5' },
        { label: '2xl:Full', value: '2xl:w-full' },
        { label: '2xl:Half', value: '2xl:w-1/2' },
        { label: '2xl:Third', value: '2xl:w-1/3' },
        { label: '2xl:Two Thirds', value: '2xl:w-2/3' },
        { label: '2xl:Quarter', value: '2xl:w-1/4' },
        { label: '2xl:Three Quarters', value: '2xl:w-3/4' },
        { label: '2xl:One Fifth', value: '2xl:w-1/5' },
        { label: '2xl:Two Fifths', value: '2xl:w-2/5' },
        { label: '2xl:Three Fifths', value: '2xl:w-3/5' },
        { label: '2xl:Four Fifths', value: '2xl:w-4/5' },
      ],
    },
  ],
}
