name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Prepare the .env file locally
      - name: Prepare .env file
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}
          NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL }}
          PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
          PREVIEW_SECRET: ${{ secrets.PREVIEW_SECRET }}
          APP_PATH: ${{ secrets.APP_PATH }}
        run: |
          cat << 'EOL' > .env
          SERVER_PASSWORD=$SERVER_PASSWORD
          CRON_SECRET=$CRON_SECRET
          DATABASE_URI=$DATABASE_URI
          NEXT_PUBLIC_SERVER_URL=$NEXT_PUBLIC_SERVER_URL
          PAYLOAD_SECRET=$PAYLOAD_SECRET
          PREVIEW_SECRET=$PREVIEW_SECRET
          APP_PATH=$APP_PATH
          EOL

      # Step 2: Copy the .env file to the server
      - name: Copy .env file to server
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          APP_PATH: ${{ secrets.APP_PATH }}
        run: |
          sshpass -p "$SERVER_PASSWORD" scp -o StrictHostKeyChecking=no -P "$SSH_PORT" .env "$SSH_USERNAME@$SERVER_IP:$APP_PATH/.env"

      # Step 3: SSH into the server and run deployment commands
      - name: Deploy application
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          APP_PATH: ${{ secrets.APP_PATH }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no -p "$SSH_PORT" "$SSH_USERNAME@$SERVER_IP" << 'EOF'
            docker builder prune -f
            cd "$APP_PATH"
            git checkout -- package.json pnpm-lock.yaml
            git pull origin master
            echo "Installing dependencies..."
            pnpm install
            docker compose build payload
            docker compose up -d
          EOF
